/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
    const ActionSheet: (typeof import('../src/utils/uniapi/prompt'))['ActionSheet'];
    const CURRENT_PLATFORM: (typeof import('../src/enums/platformEnum'))['CURRENT_PLATFORM'];
    const ContentTypeEnum: (typeof import('../src/enums/httpEnum'))['ContentTypeEnum'];
    const EffectScope: (typeof import('vue'))['EffectScope'];
    const HideLoading: (typeof import('../src/utils/uniapi/prompt'))['HideLoading'];
    const HideToast: (typeof import('../src/utils/uniapi/prompt'))['HideToast'];
    const Loading: (typeof import('../src/utils/uniapi/prompt'))['Loading'];
    const Modal: (typeof import('../src/utils/uniapi/prompt'))['Modal'];
    const NavMethod: (typeof import('uni-mini-router'))['NavMethod'];
    const NavTypeEnum: (typeof import('uni-mini-router'))['NavTypeEnum'];
    const NumberEnum: (typeof import('../src/enums/numberEnum'))['NumberEnum'];
    const PLATFORMS: (typeof import('../src/enums/platformEnum'))['PLATFORMS'];
    const ResultEnum: (typeof import('../src/enums/httpEnum'))['ResultEnum'];
    const Toast: (typeof import('../src/utils/uniapi/prompt'))['Toast'];
    const acceptHMRUpdate: (typeof import('pinia'))['acceptHMRUpdate'];
    const computed: (typeof import('vue'))['computed'];
    const createApp: (typeof import('vue'))['createApp'];
    const createPinia: (typeof import('pinia'))['createPinia'];
    const createRouter: (typeof import('uni-mini-router'))['createRouter'];
    const customRef: (typeof import('vue'))['customRef'];
    const defineAsyncComponent: (typeof import('vue'))['defineAsyncComponent'];
    const defineComponent: (typeof import('vue'))['defineComponent'];
    const defineStore: (typeof import('pinia'))['defineStore'];
    const effectScope: (typeof import('vue'))['effectScope'];
    const getActivePinia: (typeof import('pinia'))['getActivePinia'];
    const getCurrentInstance: (typeof import('vue'))['getCurrentInstance'];
    const getCurrentScope: (typeof import('vue'))['getCurrentScope'];
    const getCurrentWatcher: (typeof import('vue'))['getCurrentWatcher'];
    const h: (typeof import('vue'))['h'];
    const inject: (typeof import('vue'))['inject'];
    const isProxy: (typeof import('vue'))['isProxy'];
    const isReactive: (typeof import('vue'))['isReactive'];
    const isReadonly: (typeof import('vue'))['isReadonly'];
    const isRef: (typeof import('vue'))['isRef'];
    const isShallow: (typeof import('vue'))['isShallow'];
    const login: (typeof import('../src/services/api/auth'))['login'];
    const logout: (typeof import('../src/services/api/auth'))['logout'];
    const mapActions: (typeof import('pinia'))['mapActions'];
    const mapGetters: (typeof import('pinia'))['mapGetters'];
    const mapState: (typeof import('pinia'))['mapState'];
    const mapStores: (typeof import('pinia'))['mapStores'];
    const mapWritableState: (typeof import('pinia'))['mapWritableState'];
    const markRaw: (typeof import('vue'))['markRaw'];
    const nextTick: (typeof import('vue'))['nextTick'];
    const onActivated: (typeof import('vue'))['onActivated'];
    const onAddToFavorites: (typeof import('@dcloudio/uni-app'))['onAddToFavorites'];
    const onBackPress: (typeof import('@dcloudio/uni-app'))['onBackPress'];
    const onBeforeMount: (typeof import('vue'))['onBeforeMount'];
    const onBeforeUnmount: (typeof import('vue'))['onBeforeUnmount'];
    const onBeforeUpdate: (typeof import('vue'))['onBeforeUpdate'];
    const onDeactivated: (typeof import('vue'))['onDeactivated'];
    const onError: (typeof import('@dcloudio/uni-app'))['onError'];
    const onErrorCaptured: (typeof import('vue'))['onErrorCaptured'];
    const onHide: (typeof import('@dcloudio/uni-app'))['onHide'];
    const onLaunch: (typeof import('@dcloudio/uni-app'))['onLaunch'];
    const onLoad: (typeof import('@dcloudio/uni-app'))['onLoad'];
    const onMounted: (typeof import('vue'))['onMounted'];
    const onNavigationBarButtonTap: (typeof import('@dcloudio/uni-app'))['onNavigationBarButtonTap'];
    const onNavigationBarSearchInputChanged: (typeof import('@dcloudio/uni-app'))['onNavigationBarSearchInputChanged'];
    const onNavigationBarSearchInputClicked: (typeof import('@dcloudio/uni-app'))['onNavigationBarSearchInputClicked'];
    const onNavigationBarSearchInputConfirmed: (typeof import('@dcloudio/uni-app'))['onNavigationBarSearchInputConfirmed'];
    const onNavigationBarSearchInputFocusChanged: (typeof import('@dcloudio/uni-app'))['onNavigationBarSearchInputFocusChanged'];
    const onPageNotFound: (typeof import('@dcloudio/uni-app'))['onPageNotFound'];
    const onPageScroll: (typeof import('@dcloudio/uni-app'))['onPageScroll'];
    const onPullDownRefresh: (typeof import('@dcloudio/uni-app'))['onPullDownRefresh'];
    const onReachBottom: (typeof import('@dcloudio/uni-app'))['onReachBottom'];
    const onReady: (typeof import('@dcloudio/uni-app'))['onReady'];
    const onRenderTracked: (typeof import('vue'))['onRenderTracked'];
    const onRenderTriggered: (typeof import('vue'))['onRenderTriggered'];
    const onResize: (typeof import('@dcloudio/uni-app'))['onResize'];
    const onScopeDispose: (typeof import('vue'))['onScopeDispose'];
    const onServerPrefetch: (typeof import('vue'))['onServerPrefetch'];
    const onShareAppMessage: (typeof import('@dcloudio/uni-app'))['onShareAppMessage'];
    const onShareTimeline: (typeof import('@dcloudio/uni-app'))['onShareTimeline'];
    const onShow: (typeof import('@dcloudio/uni-app'))['onShow'];
    const onTabItemTap: (typeof import('@dcloudio/uni-app'))['onTabItemTap'];
    const onThemeChange: (typeof import('@dcloudio/uni-app'))['onThemeChange'];
    const onUnhandledRejection: (typeof import('@dcloudio/uni-app'))['onUnhandledRejection'];
    const onUnload: (typeof import('@dcloudio/uni-app'))['onUnload'];
    const onUnmounted: (typeof import('vue'))['onUnmounted'];
    const onUpdated: (typeof import('vue'))['onUpdated'];
    const onWatcherCleanup: (typeof import('vue'))['onWatcherCleanup'];
    const provide: (typeof import('vue'))['provide'];
    const reactive: (typeof import('vue'))['reactive'];
    const readonly: (typeof import('vue'))['readonly'];
    const ref: (typeof import('vue'))['ref'];
    const refreshAccessToken: (typeof import('../src/services/api/auth'))['refreshAccessToken'];
    const resolveComponent: (typeof import('vue'))['resolveComponent'];
    const setActivePinia: (typeof import('pinia'))['setActivePinia'];
    const setMapStoreSuffix: (typeof import('pinia'))['setMapStoreSuffix'];
    const shallowReactive: (typeof import('vue'))['shallowReactive'];
    const shallowReadonly: (typeof import('vue'))['shallowReadonly'];
    const shallowRef: (typeof import('vue'))['shallowRef'];
    const storeToRefs: (typeof import('pinia'))['storeToRefs'];
    const toRaw: (typeof import('vue'))['toRaw'];
    const toRef: (typeof import('vue'))['toRef'];
    const toRefs: (typeof import('vue'))['toRefs'];
    const toValue: (typeof import('vue'))['toValue'];
    const triggerRef: (typeof import('vue'))['triggerRef'];
    const unref: (typeof import('vue'))['unref'];
    const useAttrs: (typeof import('vue'))['useAttrs'];
    const useAuthStore: (typeof import('../src/stores/modules/auth'))['useAuthStore'];
    const useCssModule: (typeof import('vue'))['useCssModule'];
    const useCssVars: (typeof import('vue'))['useCssVars'];
    const useGlobalStyle: (typeof import('../src/hooks/useGlobalStyle'))['useGlobalStyle'];
    const useId: (typeof import('vue'))['useId'];
    const useModel: (typeof import('vue'))['useModel'];
    const useRoute: (typeof import('uni-mini-router'))['useRoute'];
    const useRouter: (typeof import('uni-mini-router'))['useRouter'];
    const useSlots: (typeof import('vue'))['useSlots'];
    const useTemplateRef: (typeof import('vue'))['useTemplateRef'];
    const watch: (typeof import('vue'))['watch'];
    const watchEffect: (typeof import('vue'))['watchEffect'];
    const watchPostEffect: (typeof import('vue'))['watchPostEffect'];
    const watchSyncEffect: (typeof import('vue'))['watchSyncEffect'];
}
// for type re-export
declare global {
    // @ts-ignore
    export type {
        Component,
        Slot,
        Slots,
        ComponentPublicInstance,
        ComputedRef,
        DirectiveBinding,
        ExtractDefaultPropTypes,
        ExtractPropTypes,
        ExtractPublicPropTypes,
        InjectionKey,
        PropType,
        Ref,
        ShallowRef,
        MaybeRef,
        MaybeRefOrGetter,
        VNode,
        WritableComputedRef
    } from 'vue';
    import('vue');
    // @ts-ignore
    export type { LoginDto, RefreshDto } from '../src/services/dto/auth';
    import('../src/services/dto/auth');
    // @ts-ignore
    export type { PageDto } from '../src/services/dto/common';
    import('../src/services/dto/common');
    // @ts-ignore
    export type { LoginVo } from '../src/services/vo/auth';
    import('../src/services/vo/auth');
    // @ts-ignore
    export type { BaseResponse } from '../src/services/vo/common';
    import('../src/services/vo/common');
    // @ts-ignore
    export type { ResultEnum, ContentTypeEnum } from '../src/enums/httpEnum';
    import('../src/enums/httpEnum');
    // @ts-ignore
    export type { NumberEnum } from '../src/enums/numberEnum';
    import('../src/enums/numberEnum');
    // @ts-ignore
    export type { PLATFORMS } from '../src/enums/platformEnum';
    import('../src/enums/platformEnum');
}
